package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Project itfinland")
    void generatedTest() {
        step("open \"https://itfinland.com/\"", () -> {
            step("// todo: just add selenium action");
        });

        step("Check title NERDSBAY", () -> {
            step("// todo: just add selenium action");
        });

        step("Check menu For companies", () -> {
            step("// todo: just add selenium action");
        });

        step("Check menu For IT professionals", () -> {
            step("// todo: just add selenium action");
        });

        step("Check menu Contact us", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://itfinland.com/'", () ->
            open("https://itfinland.com/"));

        step("Page title should have text 'IT Finland'", () -> {
            String expectedTitle = "IT Finland";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://itfinland.com/'", () ->
            open("https://itfinland.com/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}